# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b170e9ae5aa4445eaae7680a514c34e0262e929f35745a50cc3d757d7c61829ff3a63c694d97d988ce8e1e4eaa86dada5bada03133996a62bd957bfac094681d

test:
  secret_key_base: 7a5a89c016e40b042c8b49ac362ba1bf397ce846d4face8e8b76a15d2183b9c8e04a820395abf694a38acdf27260d390113f56b57cdfa2a93e75e9b8cb4d2b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
